### ISSUE TITLE
Query about update

### ISSUE THREAD

**Issue by XianyuanLiu** [criteo-research/pytorch-ada#15]
Hi, 

I find PyTorch-Lightning has updated to 1.0.2 and change the log metric. Could you please tell me if you'll update Pytorch-Ada? Many thanks!

**Comment by ccrndn** [comment]
Hi XianyuanLiu,
Before migrating to pytorch 1.0.2 (or 1.0.3), we have to check first that the [2 issues](https://github.com/criteo-research/pytorch-ada/blob/99885f07f611e8827071adf62c63689fad96d5e8/docs/known_issues.rst) that made us keep version 0.7.3 are now fixed.

**Comment by XianyuanLiu** [comment]
Got it. Many thanks!
